### ISSUE TITLE
PLUGIN_FAILURE and no row written to payu_latam_transactions

### ISSUE THREAD

**Issue by kevinpostlewaite** [killbill/killbill-payu-latam-plugin#1]
It looks like there are occasionally instances where we are getting PLUGIN_FAILURE for payment transactions and no rows are being written to payu_latam_transactions (or responses as well). Is this expected? (I would expect a row to be written to transactions in case of gateway failure and I would expect that if we are failing before connecting to the gateway that this would probably be because of a bug of ours).

Here's a query that will identify this case (although it looks like ALL plugin failures at the moment do not write to payu_latam_transactions)
SELECT
   distinct p.id
FROM
    payments p
    INNER JOIN payment_transactions pt on
        p.id=pt.payment_id
        AND pt.transaction_status='PLUGIN_FAILURE'
    INNER JOIN payment_methods pm on
        p.payment_method_id=pm.id
        AND pm.plugin_name='killbill-payu-latam'
    LEFT OUTER JOIN payu_latam_transactions plt on
        pt.id=plt.kb_payment_transaction_id
WHERE 1=1
    AND p.tenant_record_id=7
    AND plt.kb_payment_transaction_id is null

**Comment by pierre** [comment]
`PLUGIN_FAILURE` indicates a fatal error in the plugin (the call wasn't attempted), whereas `PAYMENT_FAILURE` indicates the call went through, but the payment method couldn't be charged.

* A response row will always be created if we are able to contact the gateway (`PAYMENT_FAILURE`, `SUCCESS` or `PENDING`)
* A transaction row is created only if the payment is successful (not in case of `PLUGIN_FAILURE` nor `PAYMENT_FAILURE`)

Note that I made some improvements regarding network connection errors when contacting the gateway (starting with https://github.com/killbill/killbill-plugin-framework-ruby/commit/27b2dc88f47eaa5144271c6fefa1611ae66dfb8b).

**Comment by kevinpostlewaite** [comment]
This can be closed.
