### ISSUE TITLE
Should this be working?

### ISSUE THREAD

**Issue by github-contenta** [killbill/killbill-payu-latam-plugin#4]
I'm just starting with KillBill, so I'm not sure if I'm doing anything wrong. The plugin is marked as "STOPPED" in Kaui Plugins page. My KillBill version is 20.5.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
